import { Inter } from "next/font/google";
import "./globals.css";
import "./loading.css";
import Navbar from "@/components/Navbar";
const inter = Inter({ subsets: ["latin"] });
import { Suspense } from "react";
import ProgressProvider from "@/components/ProgressProvider";

export const metadata = {
  title: "To-DO app",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <link rel="icon" type="image/png" sizes="48x48" href="/img/favicon.png"></link>
      <Suspense>
        <ProgressProvider>
      <body className={`${inter.className} absolute top-0 left-0 -z-[2] h-screen w-screen bg-gradient-to-tr from-[#7bb1bb] to-transparent ` }>
      <Navbar/>
      {children}
      </body>
      </ProgressProvider>
      </Suspense>
    </html>
  );
}
